// AUTO-GENERATED by scripts/extract-stats.ts — DO NOT EDIT
// Generated: 2026-04-17T06:24:46.772Z

export const stats = {
  "extractDate": "2026-04-17T06:24:46.762Z",
  "source": "Datos Abiertos CDMX - Remuneraciones de Servidores Públicos",
  "totalServidores": 246821,
  "totalSectors": 73,
  "avgSalary": 13197.72,
  "medianSalary": 10410,
  "minSalary": 461,
  "maxSalary": 111178,
  "p25": 8115,
  "p50": 10410,
  "p75": 16451,
  "p90": 21943,
  "genderGapPercent": 3.62,
  "hombres": 140784,
  "mujeres": 106036,
  "avgSalaryMale": 13406.09,
  "avgSalaryFemale": 12920.43,
  "salaryDistribution": [
    {
      "label": "Menos de $5K",
      "count": 10904
    },
    {
      "label": "$5K - $10K",
      "count": 104820
    },
    {
      "label": "$10K - $20K",
      "count": 100920
    },
    {
      "label": "$20K - $40K",
      "count": 23998
    },
    {
      "label": "Más de $40K",
      "count": 4653
    }
  ],
  "ageDistribution": [
    {
      "label": "18-25",
      "count": 8402
    },
    {
      "label": "26-35",
      "count": 50187
    },
    {
      "label": "36-45",
      "count": 97615
    },
    {
      "label": "46-55",
      "count": 64841
    },
    {
      "label": "56+",
      "count": 25766
    }
  ],
  "contractTypes": [
    {
      "label": "BASE",
      "count": 113346
    },
    {
      "label": "LISTA DE RAYA BASE",
      "count": 51440
    },
    {
      "label": "HABERES",
      "count": 39672
    },
    {
      "label": "PROVISIONAL",
      "count": 27015
    },
    {
      "label": "HONORARIOS",
      "count": 14648
    },
    {
      "label": "EVENTUAL",
      "count": 399
    },
    {
      "label": "CARACTER SOCIAL",
      "count": 301
    }
  ],
  "salaryByAge": [
    {
      "label": "18-25",
      "avg": 10680.09
    },
    {
      "label": "26-35",
      "avg": 13543.98
    },
    {
      "label": "36-45",
      "avg": 13016.96
    },
    {
      "label": "46-55",
      "avg": 13735.79
    },
    {
      "label": "56+",
      "avg": 12675.32
    }
  ],
  "personalTypes": [
    {
      "label": "SINDICALIZADOS",
      "count": 99212
    },
    {
      "label": "HABERES",
      "count": 37200
    },
    {
      "label": "CONFIANZA",
      "count": 32171
    },
    {
      "label": "ESTABILIDAD LABORAL",
      "count": 27015
    },
    {
      "label": "BASE NO SINDICALIZADO",
      "count": 21111
    },
    {
      "label": "HONORARIOS",
      "count": 14648
    },
    {
      "label": "ESTRUCTURA",
      "count": 10949
    },
    {
      "label": "INTERINATO",
      "count": 2159
    },
    {
      "label": "LISTA DE RAYA NO SINDICALIZADO",
      "count": 1656
    },
    {
      "label": "EVENTUALES",
      "count": 399
    },
    {
      "label": "CARACTER SOCIAL",
      "count": 301
    }
  ],
  "top15Sectors": [
    {
      "name": "SECRETARIA DE SEGURIDAD CIUDADANA DE LA CDMX",
      "count": 49765,
      "avgSalary": 16654.41,
      "avgMale": 17125.5,
      "avgFemale": 15684.92
    },
    {
      "name": "SECRETARIA DE SALUD DE LA CDMX",
      "count": 23591,
      "avgSalary": 17269.21,
      "avgMale": 17268.23,
      "avgFemale": 17269.84
    },
    {
      "name": "FISCALIA GENERAL DE JUSTICIA DE LA CIUDAD DE MEXICO",
      "count": 14620,
      "avgSalary": 22479.68,
      "avgMale": 23550.25,
      "avgFemale": 21152.25
    },
    {
      "name": "SISTEMA DE AGUAS DE LA CIUDAD DE MEXICO",
      "count": 12316,
      "avgSalary": 9839.22,
      "avgMale": 9941.81,
      "avgFemale": 9492.48
    },
    {
      "name": "ALCALDIA DE IZTAPALAPA",
      "count": 12070,
      "avgSalary": 8811.76,
      "avgMale": 8887.52,
      "avgFemale": 8714.13
    },
    {
      "name": "ALCALDIA DE GUSTAVO A. MADERO",
      "count": 10661,
      "avgSalary": 9384.83,
      "avgMale": 9508.06,
      "avgFemale": 9226.13
    },
    {
      "name": "ALCALDIA DE CUAUHTEMOC",
      "count": 9009,
      "avgSalary": 9316.04,
      "avgMale": 9376.04,
      "avgFemale": 9234.84
    },
    {
      "name": "ALCALDIA DE VENUSTIANO CARRANZA",
      "count": 8349,
      "avgSalary": 8874.61,
      "avgMale": 9088.06,
      "avgFemale": 8614.86
    },
    {
      "name": "SECRETARIA DE ADMINISTRACION Y FINANZAS DE LA CDMX",
      "count": 7985,
      "avgSalary": 13626.8,
      "avgMale": 14422.75,
      "avgFemale": 12919.16
    },
    {
      "name": "ALCALDIA DE COYOACAN",
      "count": 6783,
      "avgSalary": 9132.19,
      "avgMale": 9123.96,
      "avgFemale": 9143.42
    },
    {
      "name": "ALCALDIA DE ALVARO OBREGON",
      "count": 6159,
      "avgSalary": 9439.79,
      "avgMale": 9295.43,
      "avgFemale": 9648.11
    },
    {
      "name": "ALCALDIA DE BENITO JUAREZ",
      "count": 5890,
      "avgSalary": 9726.76,
      "avgMale": 9695.53,
      "avgFemale": 9777.47
    },
    {
      "name": "ALCALDIA DE XOCHIMILCO",
      "count": 5568,
      "avgSalary": 8852.4,
      "avgMale": 8900.5,
      "avgFemale": 8784
    },
    {
      "name": "ALCALDIA DE IZTACALCO",
      "count": 5434,
      "avgSalary": 9475.06,
      "avgMale": 9541.12,
      "avgFemale": 9391.37
    },
    {
      "name": "ALCALDIA DE TLALPAN",
      "count": 5388,
      "avgSalary": 9412.8,
      "avgMale": 9587.02,
      "avgFemale": 9172.03
    }
  ],
  "allSectors": [
    {
      "name": "SECRETARIA DE SEGURIDAD CIUDADANA DE LA CDMX",
      "count": 49765,
      "avgSalary": 16654.41,
      "avgMale": 17125.5,
      "avgFemale": 15684.92
    },
    {
      "name": "SECRETARIA DE SALUD DE LA CDMX",
      "count": 23591,
      "avgSalary": 17269.21,
      "avgMale": 17268.23,
      "avgFemale": 17269.84
    },
    {
      "name": "FISCALIA GENERAL DE JUSTICIA DE LA CIUDAD DE MEXICO",
      "count": 14620,
      "avgSalary": 22479.68,
      "avgMale": 23550.25,
      "avgFemale": 21152.25
    },
    {
      "name": "SISTEMA DE AGUAS DE LA CIUDAD DE MEXICO",
      "count": 12316,
      "avgSalary": 9839.22,
      "avgMale": 9941.81,
      "avgFemale": 9492.48
    },
    {
      "name": "ALCALDIA DE IZTAPALAPA",
      "count": 12070,
      "avgSalary": 8811.76,
      "avgMale": 8887.52,
      "avgFemale": 8714.13
    },
    {
      "name": "ALCALDIA DE GUSTAVO A. MADERO",
      "count": 10661,
      "avgSalary": 9384.83,
      "avgMale": 9508.06,
      "avgFemale": 9226.13
    },
    {
      "name": "ALCALDIA DE CUAUHTEMOC",
      "count": 9009,
      "avgSalary": 9316.04,
      "avgMale": 9376.04,
      "avgFemale": 9234.84
    },
    {
      "name": "ALCALDIA DE VENUSTIANO CARRANZA",
      "count": 8349,
      "avgSalary": 8874.61,
      "avgMale": 9088.06,
      "avgFemale": 8614.86
    },
    {
      "name": "SECRETARIA DE ADMINISTRACION Y FINANZAS DE LA CDMX",
      "count": 7985,
      "avgSalary": 13626.8,
      "avgMale": 14422.75,
      "avgFemale": 12919.16
    },
    {
      "name": "ALCALDIA DE COYOACAN",
      "count": 6783,
      "avgSalary": 9132.19,
      "avgMale": 9123.96,
      "avgFemale": 9143.42
    },
    {
      "name": "ALCALDIA DE ALVARO OBREGON",
      "count": 6159,
      "avgSalary": 9439.79,
      "avgMale": 9295.43,
      "avgFemale": 9648.11
    },
    {
      "name": "ALCALDIA DE BENITO JUAREZ",
      "count": 5890,
      "avgSalary": 9726.76,
      "avgMale": 9695.53,
      "avgFemale": 9777.47
    },
    {
      "name": "ALCALDIA DE XOCHIMILCO",
      "count": 5568,
      "avgSalary": 8852.4,
      "avgMale": 8900.5,
      "avgFemale": 8784
    },
    {
      "name": "ALCALDIA DE IZTACALCO",
      "count": 5434,
      "avgSalary": 9475.06,
      "avgMale": 9541.12,
      "avgFemale": 9391.37
    },
    {
      "name": "ALCALDIA DE TLALPAN",
      "count": 5388,
      "avgSalary": 9412.8,
      "avgMale": 9587.02,
      "avgFemale": 9172.03
    },
    {
      "name": "ALCALDIA DE MIGUEL HIDALGO",
      "count": 5249,
      "avgSalary": 9775.56,
      "avgMale": 9842.09,
      "avgFemale": 9667.47
    },
    {
      "name": "ALCALDIA DE AZCAPOTZALCO",
      "count": 5102,
      "avgSalary": 9454.82,
      "avgMale": 9522.76,
      "avgFemale": 9360.32
    },
    {
      "name": "SECRETARIA DE OBRAS Y SERVICIOS DE LA CDMX",
      "count": 5090,
      "avgSalary": 10759.26,
      "avgMale": 11216.42,
      "avgFemale": 10059.88
    },
    {
      "name": "ALCALDIA DE TLAHUAC",
      "count": 5057,
      "avgSalary": 9205.69,
      "avgMale": 9415.31,
      "avgFemale": 8978.9
    },
    {
      "name": "SECRETARIA DE INCLUSION Y BIENESTAR SOCIAL DE LA CDMX",
      "count": 5010,
      "avgSalary": 12846.45,
      "avgMale": 12704.15,
      "avgFemale": 12906.68
    },
    {
      "name": "CONSEJERIA JURIDICA Y DE SERVICIOS LEGALES DE LA CDMX",
      "count": 4632,
      "avgSalary": 15565.87,
      "avgMale": 16294.71,
      "avgFemale": 14961.92
    },
    {
      "name": "ALCALDIA DE CUAJIMALPA DE MORELOS",
      "count": 4393,
      "avgSalary": 9322.57,
      "avgMale": 9845.13,
      "avgFemale": 8759.22
    },
    {
      "name": "SECRETARIA DEL MEDIO AMBIENTE DE LA CDMX",
      "count": 4041,
      "avgSalary": 11469.66,
      "avgMale": 11419.9,
      "avgFemale": 11541.12
    },
    {
      "name": "ALCALDIA DE MILPA ALTA",
      "count": 3805,
      "avgSalary": 9043.52,
      "avgMale": 9379.19,
      "avgFemale": 8612.1
    },
    {
      "name": "ALCALDIA DE LA MAGDALENA CONTRERAS",
      "count": 3699,
      "avgSalary": 9209.46,
      "avgMale": 9635.95,
      "avgFemale": 8676.94
    },
    {
      "name": "HEROICO CUERPO DE BOMBEROS DEL D. F.",
      "count": 2003,
      "avgSalary": 17065.6,
      "avgMale": 17217.24,
      "avgFemale": 16481.83
    },
    {
      "name": "SECRETARIA DE MOVILIDAD DE LA CDMX",
      "count": 1669,
      "avgSalary": 14923.73,
      "avgMale": 15809.05,
      "avgFemale": 13613.53
    },
    {
      "name": "SECRETARIA DE CULTURA DE LA CDMX",
      "count": 1358,
      "avgSalary": 13286.71,
      "avgMale": 13378.1,
      "avgFemale": 13161.88
    },
    {
      "name": "SECRETARIA DE GOBIERNO DE LA CDMX",
      "count": 1313,
      "avgSalary": 15084.94,
      "avgMale": 16310.56,
      "avgFemale": 13930.02
    },
    {
      "name": "\"INSTITUTO DE ESTUDIOS SUPERIORES DE LA CIUDAD DE MEXICO \"\"ROSARIO CASTELLANOS\"\"\"",
      "count": 1173,
      "avgSalary": 20267.63,
      "avgMale": 19767.54,
      "avgFemale": 20733.93
    },
    {
      "name": "\"SECRETARIA DE EDUCACION",
      "count": 1039,
      "avgSalary": 0,
      "avgMale": 0,
      "avgFemale": 0
    },
    {
      "name": "AGENCIA DIGITAL DE INNOVACION PUBLICA",
      "count": 767,
      "avgSalary": 18456.45,
      "avgMale": 19796.75,
      "avgFemale": 17301.58
    },
    {
      "name": "SECRETARIA DE DESARROLLO URBANO Y VIVIENDA DE LA CDMX",
      "count": 745,
      "avgSalary": 14162.16,
      "avgMale": 15130.09,
      "avgFemale": 13237.41
    },
    {
      "name": "SECRETARIA DE LAS MUJERES DE LA CDMX",
      "count": 721,
      "avgSalary": 14788.81,
      "avgMale": 13664.17,
      "avgFemale": 14933.13
    },
    {
      "name": "SECRETARIA DE LA CONTRALORIA GENERAL DE LA CDMX",
      "count": 707,
      "avgSalary": 21036.09,
      "avgMale": 22582.67,
      "avgFemale": 19735.19
    },
    {
      "name": "SECRETARIA DE TRABAJO Y FOMENTO AL EMPLEO EN LA CDMX",
      "count": 595,
      "avgSalary": 13592.8,
      "avgMale": 15082.91,
      "avgFemale": 12444.18
    },
    {
      "name": "JEFATURA DE GOBIERNO DE LA CDMX",
      "count": 554,
      "avgSalary": 17144.53,
      "avgMale": 18877.39,
      "avgFemale": 15667.27
    },
    {
      "name": "SECRETARIA DE DESARROLLO ECONOMICO DE LA CDMX",
      "count": 540,
      "avgSalary": 13348.06,
      "avgMale": 13742.48,
      "avgFemale": 12900.63
    },
    {
      "name": "\"COORDINACION GENERAL DEL CENTRO DE COMANDO",
      "count": 487,
      "avgSalary": 0,
      "avgMale": 0,
      "avgFemale": 0
    },
    {
      "name": "UNIVERSIDAD DE LA POLICIA DE LA CIUDAD DE MEXICO",
      "count": 362,
      "avgSalary": 12515.1,
      "avgMale": 13249.15,
      "avgFemale": 11577.91
    },
    {
      "name": "SECRETARIA DE GESTION INTEGRAL DE RIESGOS Y PROTECCION CIVIL DE LA CDMX",
      "count": 343,
      "avgSalary": 18285.9,
      "avgMale": 18052.52,
      "avgFemale": 18624.29
    },
    {
      "name": "PLANTA PRODUCTORA DE MEZCLAS ASFALTICAS",
      "count": 293,
      "avgSalary": 12988.54,
      "avgMale": 13393.5,
      "avgFemale": 11648.57
    },
    {
      "name": "ORGANISMO REGULADOR DE TRANSPORTE",
      "count": 285,
      "avgSalary": 13412.28,
      "avgMale": 14156.85,
      "avgFemale": 12116.43
    },
    {
      "name": "UNIVERSIDAD DE LA SALUD",
      "count": 246,
      "avgSalary": 31142.85,
      "avgMale": 31099.35,
      "avgFemale": 31180.41
    },
    {
      "name": "CENTRO DE CONCILIACION LABORAL DE LA CDMX",
      "count": 222,
      "avgSalary": 21371.37,
      "avgMale": 21003.45,
      "avgFemale": 21854.26
    },
    {
      "name": "PROCURADURÍA SOCIAL DE LA CUIDAD DE MEXICO",
      "count": 210,
      "avgSalary": 11205.71,
      "avgMale": 11484.96,
      "avgFemale": 10956.66
    },
    {
      "name": "INSTITUTO DEL DEPORTE DE LA CIUDAD DE MEXICO",
      "count": 191,
      "avgSalary": 10990.5,
      "avgMale": 11187.67,
      "avgFemale": 10822.04
    },
    {
      "name": "SECRETARIA DE PUEBLOS Y BARRIOS ORIGINARIOS Y COMUNIDADES INDIGENAS RESIDENTES DE LA CDMX",
      "count": 159,
      "avgSalary": 17594.14,
      "avgMale": 17354.55,
      "avgFemale": 17808.06
    },
    {
      "name": "SECRETARIA DE TURISMO DE LA CDMX",
      "count": 150,
      "avgSalary": 20491.73,
      "avgMale": 22210.97,
      "avgFemale": 19280.44
    },
    {
      "name": "CAJA DE PREVISION DE LA POLICIA AUXILIAR DE LA CDMX",
      "count": 144,
      "avgSalary": 15209.36,
      "avgMale": 17189.77,
      "avgFemale": 13336
    },
    {
      "name": "FIDEICOMISO BIENESTAR EDUCATIVO DE LA CIUDAD DE MEXICO",
      "count": 133,
      "avgSalary": 18423.59,
      "avgMale": 16949.28,
      "avgFemale": 19400.31
    },
    {
      "name": "AGENCIA DE ATENCION ANIMAL DE LA CDMX",
      "count": 86,
      "avgSalary": 20146.72,
      "avgMale": 21986.21,
      "avgFemale": 19001.38
    },
    {
      "name": "DIR. GRAL. DE LA AGENCIA DE PROTECC. SANITARIA DE LA CDMX",
      "count": 78,
      "avgSalary": 21809.86,
      "avgMale": 23099.7,
      "avgFemale": 20452.13
    },
    {
      "name": "INSTITUTO PARA LA ATENCION Y PREVENCION DE LAS ADICCIONES EN LA CD. DE MEX.",
      "count": 69,
      "avgSalary": 26213.83,
      "avgMale": 30156.06,
      "avgFemale": 22804.32
    },
    {
      "name": "SERVICIO DE MEDIOS PUBLICOS DE LA CIUDAD DE MEXICO",
      "count": 68,
      "avgSalary": 18734.79,
      "avgMale": 18975.25,
      "avgFemale": 18391.29
    },
    {
      "name": "COORDINACION GENERAL DE LA AUTORIDAD DEL CENTRO HISTORICO DE LA CDMX",
      "count": 66,
      "avgSalary": 18400.23,
      "avgMale": 21387.34,
      "avgFemale": 13501.36
    },
    {
      "name": "FIDEICOMISO MUSEO DE ARTE POPULAR DE ARTE MEXICANO",
      "count": 63,
      "avgSalary": 15463.54,
      "avgMale": 15903.33,
      "avgFemale": 14518
    },
    {
      "name": "INSTITUTO DE EDUCACIÓN MEDIA SUPERIOR DEL DISTRITO FEDERAL",
      "count": 55,
      "avgSalary": 15875.09,
      "avgMale": 16373.76,
      "avgFemale": 15459.53
    },
    {
      "name": "CAJA DE PREVISION P/TRABAJADORES A LISTA DE RAYA DEL GOB.DE LA CDMX",
      "count": 54,
      "avgSalary": 9227.61,
      "avgMale": 10007.69,
      "avgFemale": 8503.25
    },
    {
      "name": "CAJA DE PREVISION DE LA POLICIA PREVENTIVA DE LA CDMX",
      "count": 40,
      "avgSalary": 13466.88,
      "avgMale": 13362.26,
      "avgFemale": 13561.52
    },
    {
      "name": "COMISION EJECUTIVA DE ATENCION A VICTIMAS DE LA CIUDAD DE MEXICO",
      "count": 37,
      "avgSalary": 18589.68,
      "avgMale": 26072.61,
      "avgFemale": 11500.58
    },
    {
      "name": "ESCUELA DE ADMINISTRACIÓN PÚBLICA DE LA CDMX",
      "count": 23,
      "avgSalary": 18452.48,
      "avgMale": 21185.09,
      "avgFemale": 15947.58
    },
    {
      "name": "INSTANCIA EJECUTORA DEL SISTEMA INTEGRAL DE DERECHOS HUMANOS DE LA CIUDAD DE MEXICO",
      "count": 22,
      "avgSalary": 28019.77,
      "avgMale": 30793.9,
      "avgFemale": 25708
    },
    {
      "name": "PROCURADURÍA AMBIENTAL Y DEL ORDENAMIENTO TERRITORIAL DEL DISTRITO FEDERAL",
      "count": 18,
      "avgSalary": 11129,
      "avgMale": 11129,
      "avgFemale": 11129
    },
    {
      "name": "DIR. GRAL. DEL MECANISMO DE PROTECCION INTEGRAL DE PERSONAS DEFENSORAS DE DERECHOS HUMANOS Y PERIODISTAS DE LA CDMX",
      "count": 17,
      "avgSalary": 28748.76,
      "avgMale": 23613.6,
      "avgFemale": 30888.42
    },
    {
      "name": "FIDEICOMISO MUSEO ESTANQUILLO",
      "count": 11,
      "avgSalary": 34385,
      "avgMale": 42335.29,
      "avgFemale": 20472
    },
    {
      "name": "COMISION DE BUSQUEDA DE PERSONAS DE LA CIUDAD DE MEXICO",
      "count": 10,
      "avgSalary": 46224.7,
      "avgMale": 49469.33,
      "avgFemale": 41357.75
    },
    {
      "name": "FONDO DE DESARROLLO ECONOMICO DEL D.F. (FONDECO)",
      "count": 9,
      "avgSalary": 17211.44,
      "avgMale": 17534.8,
      "avgFemale": 16807.25
    },
    {
      "name": "INSTITUTO DE LAS PERSONAS CON DISCAPACIDAD DE LA CIUDAD DE MEXICO",
      "count": 7,
      "avgSalary": 9724.71,
      "avgMale": 9991.67,
      "avgFemale": 9524.5
    },
    {
      "name": "FIDEICOMISO PARA LA RECONSTRUCCION INTEGRAL DE LA CIUDAD DE MEXICO",
      "count": 5,
      "avgSalary": 37405.8,
      "avgMale": 42369.67,
      "avgFemale": 29960
    },
    {
      "name": "FIDEICOMISO PARA LA PROMOCIÓN Y DESARROLLO DEL CINE MEXICANO EN LA CIUDAD DE MEXICO",
      "count": 4,
      "avgSalary": 48327.25,
      "avgMale": 58630.5,
      "avgFemale": 38024
    },
    {
      "name": "CONSEJO PARA PREVENIR Y ELIMINAR LA DISCRIMINACIÓN DE LA CIUDAD DE MÉXICO",
      "count": 3,
      "avgSalary": 11129,
      "avgMale": 11129,
      "avgFemale": 11129
    },
    {
      "name": "INSTITUTO DE VERIFICACIÓN ADMINISTRATIVA DEL DISTRITO FEDERAL",
      "count": 1,
      "avgSalary": 18700,
      "avgMale": 18700,
      "avgFemale": 0
    }
  ],
  "genderGapBySector": [
    {
      "name": "COMISION EJECUTIVA DE ATENCION A VICTIMAS DE LA CIUDAD DE MEXICO",
      "avgMale": 26072.61,
      "avgFemale": 11500.58,
      "gap": 55.89
    },
    {
      "name": "FIDEICOMISO MUSEO ESTANQUILLO",
      "avgMale": 42335.29,
      "avgFemale": 20472,
      "gap": 51.64
    },
    {
      "name": "COORDINACION GENERAL DE LA AUTORIDAD DEL CENTRO HISTORICO DE LA CDMX",
      "avgMale": 21387.34,
      "avgFemale": 13501.36,
      "gap": 36.87
    },
    {
      "name": "FIDEICOMISO PARA LA PROMOCIÓN Y DESARROLLO DEL CINE MEXICANO EN LA CIUDAD DE MEXICO",
      "avgMale": 58630.5,
      "avgFemale": 38024,
      "gap": 35.15
    },
    {
      "name": "DIR. GRAL. DEL MECANISMO DE PROTECCION INTEGRAL DE PERSONAS DEFENSORAS DE DERECHOS HUMANOS Y PERIODISTAS DE LA CDMX",
      "avgMale": 23613.6,
      "avgFemale": 30888.42,
      "gap": -30.81
    },
    {
      "name": "FIDEICOMISO PARA LA RECONSTRUCCION INTEGRAL DE LA CIUDAD DE MEXICO",
      "avgMale": 42369.67,
      "avgFemale": 29960,
      "gap": 29.29
    },
    {
      "name": "ESCUELA DE ADMINISTRACIÓN PÚBLICA DE LA CDMX",
      "avgMale": 21185.09,
      "avgFemale": 15947.58,
      "gap": 24.72
    },
    {
      "name": "INSTITUTO PARA LA ATENCION Y PREVENCION DE LAS ADICCIONES EN LA CD. DE MEX.",
      "avgMale": 30156.06,
      "avgFemale": 22804.32,
      "gap": 24.38
    },
    {
      "name": "CAJA DE PREVISION DE LA POLICIA AUXILIAR DE LA CDMX",
      "avgMale": 17189.77,
      "avgFemale": 13336,
      "gap": 22.42
    },
    {
      "name": "SECRETARIA DE TRABAJO Y FOMENTO AL EMPLEO EN LA CDMX",
      "avgMale": 15082.91,
      "avgFemale": 12444.18,
      "gap": 17.49
    }
  ],
  "topPositions": [
    {
      "name": "JEFE DE GOBIERNO",
      "count": 1,
      "avgSalary": 111178
    },
    {
      "name": "COMISIONADO",
      "count": 1,
      "avgSalary": 109981
    },
    {
      "name": "SECRETARIO PARTICULAR AA",
      "count": 1,
      "avgSalary": 109981
    },
    {
      "name": "SUBSECRETARIO",
      "count": 8,
      "avgSalary": 104740
    },
    {
      "name": "ALCALDE DE LA CDMX",
      "count": 16,
      "avgSalary": 104740
    },
    {
      "name": "TESORERO",
      "count": 1,
      "avgSalary": 104740
    },
    {
      "name": "OFICIAL MAYOR SSCCDMX",
      "count": 1,
      "avgSalary": 104740
    },
    {
      "name": "SECRETARIO",
      "count": 23,
      "avgSalary": 100417.43
    },
    {
      "name": "ASESOR D",
      "count": 6,
      "avgSalary": 99967
    },
    {
      "name": "PROCURADOR FISCAL",
      "count": 1,
      "avgSalary": 99967
    }
  ],
  "seniorityDistribution": [
    {
      "label": "0-2 años",
      "count": 25636
    },
    {
      "label": "3-5 años",
      "count": 39547
    },
    {
      "label": "6-10 años",
      "count": 56712
    },
    {
      "label": "11-20 años",
      "count": 79746
    },
    {
      "label": "21-30 años",
      "count": 35191
    },
    {
      "label": "30+ años",
      "count": 9989
    }
  ],
  "salaryBySeniority": [
    {
      "label": "0-2 años",
      "avg": 12873.42,
      "count": 25477
    },
    {
      "label": "3-5 años",
      "avg": 13042.81,
      "count": 39269
    },
    {
      "label": "6-10 años",
      "avg": 13287.34,
      "count": 56322
    },
    {
      "label": "11-20 años",
      "avg": 13253.14,
      "count": 79252
    },
    {
      "label": "21-30 años",
      "avg": 13432.95,
      "count": 35036
    },
    {
      "label": "30+ años",
      "avg": 12862.13,
      "count": 9939
    }
  ],
  "avgSeniority": 11.86,
  "avgNetSalary": 11726.21,
  "avgDeduction": 1471.51,
  "avgDeductionPercent": 11.15,
  "brutoNetoByRange": [
    {
      "label": "Menos de $5K",
      "avgBruto": 3840.06,
      "avgNeto": 4010.5,
      "count": 10904
    },
    {
      "label": "$5K - $10K",
      "avgBruto": 7884.86,
      "avgNeto": 7434.85,
      "count": 104820
    },
    {
      "label": "$10K - $20K",
      "avgBruto": 14525.72,
      "avgNeto": 13016.35,
      "count": 100920
    },
    {
      "label": "$20K - $40K",
      "avgBruto": 26327.91,
      "avgNeto": 22349.43,
      "count": 23998
    },
    {
      "label": "Más de $40K",
      "avgBruto": 58289.24,
      "avgNeto": 46226.24,
      "count": 4653
    }
  ]
} as const;

export type Stats = typeof stats;
